build_from:
  aarch64: ghcr.io/home-assistant/aarch64-base:3.22
  amd64: ghcr.io/home-assistant/amd64-base:3.22
labels:
  org.opencontainers.image.title: "Firefox Home Assistant Add-on"
  org.opencontainers.image.description: "Firefox browser via linuxserver.io"
  org.opencontainers.image.source: "https://github.com/linuxserver/docker-firefox"
  org.opencontainers.image.licenses: "MIT"
